name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish
