name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d

      - name: Build package
        run: uv build

      - name: Publish package
        run: uv publish
