name: Pytest

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Tests
    runs-on: 
      - runs-on=${{ github.run_id }}
      - job=tests
      - extras=s3-cache
    steps:
      - uses: runs-on/action@v2
      - uses: actions/checkout@v5
      - uses: citizensadvice/python-uv-setup-action@v1
      - uses: extractions/setup-just@v3
      - run: just lint pytest
