name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: All Tests
    runs-on: 
      - runs-on=${{ github.run_id }}
      - job=pytest
      - extras=s3-cache
    strategy:
      matrix:
        python_version: ['3.10', '3.11', '3.12', '3.13', '3.14']
    steps:
      - uses: runs-on/action@46910bf61b41721b0579f237e186afb35477007a
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      
      - name: Setup Python
        uses: citizensadvice/python-uv-setup-action@70884aff70491439526c3e437c25803b9e67aaed
        with:
          python_version: ${{ matrix.python_version }}

      - name: Ruff Check
        run: uv run ruff check
      
      - name: Ruff Format
        run: uv run ruff format --check

      - name: ty check
        run: uv run ty check

      - name: Pytest
        run: uv run pytest

  checks-successful:
    name: All Checks Passed
    runs-on: ubuntu-latest
    if: always()
    needs: [pytest]
    steps:
      - uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35
        with:
          jobs: ${{ toJSON(needs) }}