name: Tests

on:
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: All Tests
    runs-on: 
      - runs-on=${{ github.run_id }}
      - job=pytest
      - extras=s3-cache
    steps:
      - uses: runs-on/action@v2
      - uses: actions/checkout@v5
      
      - name: Setup Python
        uses: citizensadvice/python-uv-setup-action@v1

      - name: Ruff Check
        run: uv run ruff check
      
      - name: Ruff Format
        run: uv run ruff format --check

      - name: Pytest
        run: uv run pytest
