name: Update CRD Imports

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  update-crds:
    runs-on: runs-on
    name: Update CRD Imports
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install Node
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 20

      - name: Install cdk8s
        run: npm install -g cdk8s-cli

      - name: Update CRDs
        run: cdk8s import --output ca_cdk8s_constructs/imports

      - name: Check for changes
        id: check-for-changes
        run: |
          CHANGES=$(git status --porcelain=v1 ca_cdk8s_constructs/imports)
          if [ -z "$CHANGES" ]; then
            echo "No changes to CRDs detected"
          else
            echo "Changes to CRDs detected"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0
        if: ${{ steps.check-for-changes.outputs.changes != '' }}
        with:
          branch: updates/crds
          commit-message: Update CRDs
          title: Update CRDs
          body: |
            Automated PR to update CRDs to latest version.

            The checks will not run automatically due to workflows not being able to be triggered by other workflows, but you can trigger them with:

            `git checkout origin updates/crds && git pull && git commit --allow-empty --allow-empty-message -m "" && git push`